# Numpy Practice

This section will go over exercises using numpy.

## Array Creation Basics

### Exercise 0: help() Function

In [1]:
import numpy as np

# For documentation on each function, use:
# help(np.functionName)

help(np.array)

# other functions include: arange, linspace, logspace, mat, diag, etc.
# These functions are called 'routines'.

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

### Exercise 1: Create an Array (using arange and a list)

In [2]:
a = np.arange(10)
b = np.array([[7,8,9], [10,11,12]])
c = np.arange(3.5,6.0, .5)

print('a:\n', a, '\n')
print('b:\n', b, '\n')
print('c:\n', c)

# for documentation on each function, use:
# help(np.functionName)

a:
 [0 1 2 3 4 5 6 7 8 9] 

b:
 [[ 7  8  9]
 [10 11 12]] 

c:
 [3.5 4.  4.5 5.  5.5]


Using *arange* similar to using *range*.

You can also add create an array using a list.

### Exercise 2: Reshaping Arrays

Can *reshape* an object by specifying (numColumns, numRows) in the command.



In [3]:
a = a.reshape(2, 5)
b = b.reshape(3,2)

print('a: \n', a, '\n')
print('b: \n', b)

a: 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

b: 
 [[ 7  8]
 [ 9 10]
 [11 12]]


Object a has been changed into a 5x2 matrix, and b into a 2x3 matrix.


In [4]:
a = a.reshape(5,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Now a is a 2x5 matrix.


### Exercise 3: Dimensions, Shape, and Type, Size

In [5]:
print('Information on a:\n')

print('Num. Dimensions:', a.ndim)
print('Shape:', a.shape)
print('Type:', type(a))
print('Contents Type:', a.dtype)
print('Size of a:', a.size)


Information on a:

Num. Dimensions: 2
Shape: (5, 2)
Type: <class 'numpy.ndarray'>
Contents Type: int64
Size of a: 10


### Exercise 4: Bytes

In [6]:
print('Bytes per Elements:', a.itemsize)
print('Bytes of Entire Array:', a.nbytes)

Bytes per Elements: 8
Bytes of Entire Array: 80


### Exercise 5: Array of Booleans

In [7]:
c = np.array([False, False, True, True], dtype=bool)
print('Type:', c.dtype)

Type: bool


### Exercise 6: Array Using linspace()

In [8]:
# creates an evenly spaced array of a given number of items.
# linspace(start, stop, numberOfItems) where start and stop are inclusive.
np.linspace(1,3,num=6)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [9]:
# endpoint=False -> excludes the upper bound from the calculation.
np.linspace(1,3,num=6, endpoint=False)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667])

In [10]:
# retstep=True -> returns the step value as well as the array in a list.
np.linspace(1,3,num=6,retstep=True)

(array([1. , 1.4, 1.8, 2.2, 2.6, 3. ]), 0.4)

## Array Operations

### Exercise 1: Addition

In [11]:
a = np.arange(1,6)
b = np.linspace(0.1,0.5, num=5)

print(a)
print(b)

[1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


In [12]:
# Scalar Addition
print(a+1)

[2 3 4 5 6]


In [13]:
# Vector Addition
print(a+b)

[1.1 2.2 3.3 4.4 5.5]


### Exercise 2: Multiplication

In [14]:
# Scalar Multiplication
c = 2 * a
print(c, '\n')

# Scalar Power
c = a ** 2
print(c)

[ 2  4  6  8 10] 

[ 1  4  9 16 25]


In [15]:
# Vector Multiplication
c = a * b
print(c, '\n')

# Vector Power
c = a ** b
print(c)

[0.1 0.4 0.9 1.6 2.5] 

[1.         1.14869835 1.39038917 1.74110113 2.23606798]


In [16]:
# Matrix Multiplication
a = np.arange(1,10)
a = a.reshape(3,3)

b = np.array([1,2,3])

c = a * b
print(c)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


### Exercise 3: Math Functions

In [17]:
# numpy defines PI and e, no need to import math here.
a = np.array([0, np.pi/2, 2*np.pi/3, np.pi])

b = np.cos(a)
c = np.sin(a)

print(b)
print(c)

np.e

[ 1.000000e+00  6.123234e-17 -5.000000e-01 -1.000000e+00]
[0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]


2.718281828459045

### Exercise 4: In-place Operations

It is possible to use the +=, -=, *=, /= operators on numpy arrays.

In [18]:
a = np.arange(1,6)

a += 2
print('Addition:', a)
a -= 2
print('Subtraction:', a)
a *= 2
print('Multiplication:', a)

a //= 2
print('Integer Division:', a)

a.dtype = float
a /= 2
print('Float Division:', a)

Addition: [3 4 5 6 7]
Subtraction: [1 2 3 4 5]
Multiplication: [ 2  4  6  8 10]
Integer Division: [1 2 3 4 5]
Float Division: [0.e+000 5.e-324 1.e-323 1.e-323 1.e-323]


**It is also possible to use in-place operators inside functions:**

In [19]:
def add_5(array):
    array += 5
    return array

a = add_5(np.arange(1,6))
print(a)

[ 6  7  8  9 10]


## Set and Fill Array Elements

### Setting Values

In [20]:
a = np.linspace(1,2, num=4)

a[0] = 0
a[3] = 2.35

print(a)

[0.         1.33333333 1.66666667 2.35      ]


### Filling

### Exercise 1: Scalar Fill

In [21]:
# Fill with any scalar value
a = np.empty([3,3])
a.fill(0)

b = np.empty(3)
b.fill(0.1234)

print(a, '\n')
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[0.1234 0.1234 0.1234]


#### Exercise 2: Other Fills

In [22]:
# Fill with Zeros
a = np.zeros(3)

# Fill with Ones
b = np.ones([4,2]) # use a tuple for nxn or nxm dimensions

# Identity Matrix
c = np.identity(5)

print(a, b, c, sep='\n\n', end='\n\n')

# Multi-Dimensional
a = np.zeros([3,2,3]) # create an array of three 2x3 arrays filled with zeros.
print(a)

[0. 0. 0.]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


## Slicing and Indexing

### Exercise 1: Slicing

In [23]:
# array[lower:upper:steps], steps optional, inclusive of lower bound only.

a = np.empty(4)
a.fill(2)

# fill by slicing
a[0:2] = 8
print(a, '\n')

# assigning values by slicing
a[1:4] = 11, 12, 13
print(a)

[8. 8. 2. 2.] 

[ 8. 11. 12. 13.]


### Exercise 2: Slicing with Steps

In [24]:
#fill with steps and slicing
a[1:4:2] = 5
print(a, '\n')


# slicing with steps and alternating values
a[1:4:2] = 6, 3
print(a)

[ 8.  5. 12.  5.] 

[ 8.  6. 12.  3.]


### Exercise 3: Negative Indices

In [25]:
# negative values
# -1 is the last value in the array, counts down to the left
# upper bound (-1) is not inclusive.

print(a[-3:-1])


[ 6. 12.]


### Exercise 4: Omitting Indices

In [26]:
# print from beginning up to and excluding the 2nd index.
print(a[:2])

# print from 2nd index to the end, excluding last value.
print(a[2:])

# print from -2 to 0, excluding 0.
print(a[-2:])

# fill by omitting indices
a[:2] = 1
print(a)

[8. 6.]
[12.  3.]
[12.  3.]
[ 1.  1. 12.  3.]


### Exercise 5: Slices as References

In [27]:
# can assign a slice of an array to another variable
a = np.arange(0,6)
b = a[2:5]
print(a,b,sep='\n\n')
print('\n\n')

# if any component of a sliced variable changes, the parent changes too
b[0] = 16
print(a,b,sep='\n\n')

# can be done with multi-dimensional arrays as well.

[0 1 2 3 4 5]

[2 3 4]



[ 0  1 16  3  4  5]

[16  3  4]


### Exercise 6: 2-D Indexing

In [28]:
b = np.zeros(6)
b = b.reshape(2,3)

# addressing a single value in a 2-D array
b[0,2] = 23
b[1,1] = 5
print(b,'\n\n')

# addressing a row using a single index
b[1] = 18
print(b)


[[ 0.  0. 23.]
 [ 0.  5.  0.]] 


[[ 0.  0. 23.]
 [18. 18. 18.]]


### Exercise 7: Multidimensional Slicing

In [29]:
# create an array from mulitple arrays


# addressing a column


# addressing with steps

## Advanced Indexing

### Exercise 1: Use Another Array for Index Addressing

### Exercise 2: Index with Booleans

### Exercise 3: Use Conditionals to Mask Elements in Array

## Reshaping Arrays

### Exercise 1: Reshaping