# Numpy Practice

This section will go over exercises using numpy.

## Array Creation Basics

### Exercise 0: help() Function

In [1]:
import numpy as np

# For documentation on each function, use:
# help(np.functionName)

help(np.array)

# other functions include: arange, linspace, logspace, mat, diag, etc.
# These functions are called 'routines'.

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

### Exercise 1: Create an Array (using arange and a list)

In [2]:
a = np.arange(10)
b = np.array([[7,8,9], [10,11,12]])
c = np.arange(3.5,6.0, .5)

print('a:\n', a, '\n')
print('b:\n', b, '\n')
print('c:\n', c)

# for documentation on each function, use:
# help(np.functionName)

a:
 [0 1 2 3 4 5 6 7 8 9] 

b:
 [[ 7  8  9]
 [10 11 12]] 

c:
 [3.5 4.  4.5 5.  5.5]


Using *arange* similar to using *range*.

You can also add create an array using a list.

### Exercise 2: Reshaping Arrays

Can *reshape* an object by specifying (numColumns, numRows) in the command.



In [3]:
a = a.reshape(2, 5)
b = b.reshape(3,2)

print('a: \n', a, '\n')
print('b: \n', b)

a: 
 [[0 1 2 3 4]
 [5 6 7 8 9]] 

b: 
 [[ 7  8]
 [ 9 10]
 [11 12]]


Object a has been changed into a 5x2 matrix, and b into a 2x3 matrix.


In [4]:
a = a.reshape(5,2)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Now a is a 2x5 matrix.


### Exercise 3: Dimensions, Shape, and Type, Size

In [5]:
print('Information on a:\n')

print('Num. Dimensions:', a.ndim)
print('Shape:', a.shape)
print('Type:', type(a))
print('Contents Type:', a.dtype)
print('Size of a:', a.size)


Information on a:

Num. Dimensions: 2
Shape: (5, 2)
Type: <class 'numpy.ndarray'>
Contents Type: int64
Size of a: 10


### Exercise 4: Bytes

In [6]:
print('Bytes per Elements:', a.itemsize)
print('Bytes of Entire Array:', a.nbytes)

Bytes per Elements: 8
Bytes of Entire Array: 80


### Exercise 5: Array of Booleans

In [7]:
c = np.array([False, False, True, True], dtype=bool)
print('Type:', c.dtype)

Type: bool


### Exercise 6: Array Using linspace()

In [8]:
# creates an evenly spaced array of a given number of items.
# linspace(start, stop, numberOfItems) where start and stop are inclusive.
np.linspace(1,3,num=6)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [9]:
# endpoint=False -> excludes the upper bound from the calculation.
np.linspace(1,3,num=6, endpoint=False)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667])

In [10]:
# retstep=True -> returns the step value as well as the array in a list.
np.linspace(1,3,num=6,retstep=True)

(array([1. , 1.4, 1.8, 2.2, 2.6, 3. ]), 0.4)

## Array Operations

### Exercise 1: Addition

In [11]:
a = np.arange(1,6)
b = np.linspace(0.1,0.5, num=5)

print(a)
print(b)

[1 2 3 4 5]
[0.1 0.2 0.3 0.4 0.5]


In [12]:
# Scalar Addition
print(a+1)

[2 3 4 5 6]


In [13]:
# Vector Addition
print(a+b)

[1.1 2.2 3.3 4.4 5.5]


### Exercise 2: Multiplication

In [14]:
# Scalar Multiplication
c = 2 * a
print(c, '\n')

# Scalar Power
c = a ** 2
print(c)

[ 2  4  6  8 10] 

[ 1  4  9 16 25]


In [15]:
# Vector Multiplication
c = a * b
print(c, '\n')

# Vector Power
c = a ** b
print(c)

[0.1 0.4 0.9 1.6 2.5] 

[1.         1.14869835 1.39038917 1.74110113 2.23606798]


In [16]:
# Matrix Multiplication
a = np.arange(1,10)
a = a.reshape(3,3)

b = np.array([1,2,3])

c = a * b
print(c)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


### Exercise 3: Math Functions

In [17]:
# numpy defines PI and e, no need to import math here.
a = np.array([0, np.pi/2, 2*np.pi/3, np.pi])

b = np.cos(a)
c = np.sin(a)

print(b)
print(c)

np.e

[ 1.000000e+00  6.123234e-17 -5.000000e-01 -1.000000e+00]
[0.00000000e+00 1.00000000e+00 8.66025404e-01 1.22464680e-16]


2.718281828459045

### Exercise 4: In-place Operations

It is possible to use the +=, -=, *=, /= operators on numpy arrays.

In [18]:
a = np.arange(1,6)

a += 2
print('Addition:', a)
a -= 2
print('Subtraction:', a)
a *= 2
print('Multiplication:', a)

a //= 2
print('Integer Division:', a)

a.dtype = float
a /= 2
print('Float Division:', a)

Addition: [3 4 5 6 7]
Subtraction: [1 2 3 4 5]
Multiplication: [ 2  4  6  8 10]
Integer Division: [1 2 3 4 5]
Float Division: [0.e+000 5.e-324 1.e-323 1.e-323 1.e-323]


**It is also possible to use in-place operators inside functions:**

In [19]:
def add_5(array):
    array += 5
    return array

a = add_5(np.arange(1,6))
print(a)

[ 6  7  8  9 10]


## Set and Fill Array Elements

### Setting Values

In [20]:
a = np.linspace(1,2, num=4)

a[0] = 0
a[3] = 2.35

print(a)

[0.         1.33333333 1.66666667 2.35      ]


### Filling

### Exercise 1: Scalar Fill

In [21]:
# Fill with any scalar value
a = np.empty([3,3])
a.fill(0)

b = np.empty(3)
b.fill(0.1234)

print(a, '\n')
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[0.1234 0.1234 0.1234]


#### Exercise 2: Other Fills

In [22]:
# Fill with Zeros
a = np.zeros(3)

# Fill with Ones
b = np.ones([4,2]) # use a tuple for nxn or nxm dimensions

# Identity Matrix
c = np.identity(5)

print(a, b, c, sep='\n\n', end='\n\n')

# Multi-Dimensional
a = np.zeros([3,2,3]) # create an array of three 2x3 arrays filled with zeros.
print(a)

[0. 0. 0.]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


## Slicing and Indexing

### Exercise 1: Slicing

In [23]:
# array[lower:upper:steps], steps optional, inclusive of lower bound only.

a = np.empty(4)
a.fill(2)

# fill by slicing
a[0:2] = 8
print(a, '\n')

# assigning values by slicing
a[1:4] = 11, 12, 13
print(a)

[8. 8. 2. 2.] 

[ 8. 11. 12. 13.]


### Exercise 2: Slicing with Steps

In [24]:
#fill with steps and slicing
a[1:4:2] = 5
print(a, '\n')


# slicing with steps and alternating values
a[1:4:2] = 6, 3
print(a)

[ 8.  5. 12.  5.] 

[ 8.  6. 12.  3.]


### Exercise 3: Negative Indices

In [25]:
# negative values
# -1 is the last value in the array, counts down to the left
# upper bound (-1) is not inclusive.

print(a[-3:-1])


[ 6. 12.]


### Exercise 4: Omitting Indices

In [26]:
# print from beginning up to and excluding the 2nd index.
print(a[:2])

# print from 2nd index to the end, excluding last value.
print(a[2:])

# print from -2 to 0, excluding 0.
print(a[-2:])

# fill by omitting indices
a[:2] = 1
print(a)

[8. 6.]
[12.  3.]
[12.  3.]
[ 1.  1. 12.  3.]


### Exercise 5: Slices as References

In [27]:
# can assign a slice of an array to another variable
a = np.arange(0,6)
b = a[2:5]
print(a,b,sep='\n\n')
print('\n\n')

# if any component of a sliced variable changes, the parent changes too
b[0] = 16
print(a,b,sep='\n\n')

# can be done with multi-dimensional arrays as well.

[0 1 2 3 4 5]

[2 3 4]



[ 0  1 16  3  4  5]

[16  3  4]


### Exercise 6: 2-D Indexing

In [28]:
b = np.zeros(6)
b = b.reshape(2,3)

# addressing a single value in a 2-D array
b[0,2] = 23
b[1,1] = 5
print(b,'\n\n')

# addressing a row using a single index
b[1] = 18
print(b)


[[ 0.  0. 23.]
 [ 0.  5.  0.]] 


[[ 0.  0. 23.]
 [18. 18. 18.]]


### Exercise 7: Multidimensional Slicing

In [29]:
# create an array from mulitple arrays
a = np.array([np.arange(1,5), np.arange(11,15), np.arange(21,25), np.arange(31,35)])
print(a)
print()
print(a.shape)
print()

# addressing a column
print(a[:,0]) # printed out the column as a list
print()

# addressing with steps
# Notation: a[lower:upper:steps]
print(a[2::2, ::2]) 

# Side Note:
# a[2:] returns row 2 to end as an array
# a[2::2] = returns row 2 to end in steps of 2
# a[2::2, ::2] returns the values 2 to end in steps of 2 of rows 2 to end in steps of 2

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

(4, 4)

[ 1 11 21 31]

[[21 23]]


## Advanced Indexing

### Exercise 1: Use Another Array for Index Addressing

In [30]:
a = np.arange(10,30,3)
print(a)

indexes = np.array([1,3,-1]) # type indices of the values we want to assign to x

x = a[indexes] # x is composed of the specific indices of a we assigned to indexes array.
x 

[10 13 16 19 22 25 28]


array([13, 19, 28])

### Exercise 2: Index with Booleans

In [31]:
a = np.arange(0,35,5)
print(a)
print()

mask = np.array([1,0,1,0,0,0,1], dtype='bool') # only three 'True' values.
print(mask)
print()

b = a[mask] # returns all the values of a that are 'True' in mask.
print(b)

[ 0  5 10 15 20 25 30]

[ True False  True False False False  True]

[ 0 10 30]


### Exercise 3: Use Conditionals to Mask Elements in Array

In [32]:
# returns an array of booleans that correspond to whether that value of a meets the condition.
mask2 = a < 10
print(mask2)
print()

mask3 = a > 20
print(mask3)
print()

# return an array of all the values of a that are 'True' from the masks
b = np.array([a[mask2], a[mask3]])
print(b.reshape(1,4))

[ True  True False False False False False]

[False False False False False  True  True]

[[ 0  5 25 30]]


## Reshaping Arrays

### Exercise 1: Shaping

In [33]:
# Notation: shape(numRows, numColumns)

b = np.arange(10,30)
print(b, '\n\n')

print(b.shape, '\n\n')

# will change the shape of the original array
b.shape = (5,2,2)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29] 


(20,) 


[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]

 [[18 19]
  [20 21]]

 [[22 23]
  [24 25]]

 [[26 27]
  [28 29]]]


### Exercise 2: Reshaping

In [34]:
# reshaping returns a copy of the original array in the given shape
a = np.arange(1,11)
print(a, a.shape, sep='\n', end ='\n\n')

b = a.reshape(2,5)
print(b, b.shape, sep='\n', end='\n\n')

# Shape and Reshape do not delete elements. Therefore, assigned dimensions MUST match/be possible.

[ 1  2  3  4  5  6  7  8  9 10]
(10,)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)



## Flatten Arrays 

### Exercise 1: Flatten

In [35]:
# use flatten to make arrays one-dimensional
a = np.arange(1,10)
a.shape = (3,3)

print(a, '\n\n')

b = a.flatten()
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 


[1 2 3 4 5 6 7 8 9]


### Exercise 2: Flat Attribute

In [36]:
# flat as an attribute can be assigned to a variable to traverse an array as if it were one-dimensional.

print(a, '\n\n')

c = a.flat
print(c, '\n\n')

c[1] = 26
c[5:8] = 0

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 




[[ 1 26  3]
 [ 4  5  0]
 [ 0  0  9]]


## Where Method

### Exercise 1: Using Where to Find Indices

In [37]:
# Where returns array of indices of the values that meet the expression
# Conditional returns array of booleans of whether or not the values meet the expression

a = np.linspace(0,3,6)
print(a, '\n\n')

print(a>2,'\n\n') # Conditional returns booleans in an array

b = np.where(a>2) # Where returns indices in an array
print(b,'\n\n')


# the values of a that meet a>2 using the where function for indices.
c = a[b]
print(c)

[0.  0.6 1.2 1.8 2.4 3. ] 


[False False False False  True  True] 


(array([4, 5]),) 


[2.4 3. ]


### Exercise 2: Using Where in 2-D

In [38]:
a = np.arange(0,6).reshape(2,3)
print(a, '\n\n')

# bools of the values >3
print(a>2, '\n\n') 

# returns indices of values >3
b = np.where(a>3)
print(b, '\n\n')

# get the values of a that are >3
c = a[b]
print(c)

[[0 1 2]
 [3 4 5]] 


[[False False False]
 [ True  True  True]] 


(array([1, 1]), array([1, 2])) 


[4 5]


## Array Operations - Linear Algebra

### Exercise 1: Transpose

In [45]:
# Transpose - flip the dimensions of an array.
# returns a copy of the original array with the dimensions switched.

a = np.arange(1,9).reshape(2,4)
print(a,'\n')
print(a.shape, '\n\n')

b = a.transpose()
print(b,'\n')
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]] 

(2, 4) 


[[1 5]
 [2 6]
 [3 7]
 [4 8]] 

(4, 2)


### Exercise 2: Strides

In [46]:
# Strides - tuples of byte steps in each dimension
# 8 bytes = 1 value

# Notation:
# (bytes to the next value, bytes to this index at the row below)

print(a.strides)
print()
print(a.T.strides) # transpose the strides tuple

(32, 8)

(8, 32)


### Exercise 3: Sums

In [51]:
# Sum up all elements in an array
a = np.arange(1,7).reshape(3,2)
print(a, '\n')
print('Sum of all a:', np.sum(a))

# Sum along the axes
# columns: axis=0
# rows: axis=1
print('Sum of each column:', np.sum(a, axis = 0)) 
print('Sum of each row:', np.sum(a, axis = 1))

[[1 2]
 [3 4]
 [5 6]] 

Sum of all a: 21
Sum of each column: [ 9 12]
Sum of each row: [ 3  7 11]


### Exercise 4: Product

In [52]:
# Calculate the product of all elements in an array
print(a, '\n')
print('Product of all elements in a:', a.prod())

# Product along the axes
print('Product of each column:', np.prod(a, axis=0))
print('Product of each row:', np.prod(a, axis=1))

[[1 2]
 [3 4]
 [5 6]] 

Product of all elements in a: 720
Product of each column: [15 48]
Product of each row: [ 2 12 30]


### Exercise 5: Matrix Multiplication

In [63]:
# Multiply an n=2 identity matrix with a 
# 2x2 and 2x3 matrix, respectively
a = np.eye(2)

b = np.arange(1,5).reshape(2,2)
matm_ab = np.matmul(a,b)

c = np.arange(1,7).reshape(2,3)
matm_ac = np.matmul(a,c)

print(matm_ab, '\n\n')
print(matm_ac)

[[1. 2.]
 [3. 4.]] 


[[1. 2. 3.]
 [4. 5. 6.]]


### Exercise 6: Dot Product

In [64]:
a = np.arange(1,10).reshape(3,3)
b = np.array([1,2,3])

dot_ab = np.dot(a,b)
dot_bb = np.dot(b,b)

print('Dot ab:', dot_ab)
print('Dot bb:', dot_bb)

Dot ab: [14 32 50]
Dot bb: 14


### Exercise 7: Min. and Max. (and argmin/max)

In [70]:
# Find the Min./Max. Value of an array
a = np.arange(0, 12).reshape(3,4)
print(a, '\n')

min_a = a.min()
max_a = a.max()

# Find the Min./Max. along each axis of an array
col_max = a.max(axis=0)
row_min = a.min(axis=1)

print('Min. of a:', min_a)
print('Max of a:', max_a)
print('Max along columns:', col_max)
print('Min along rows:', row_min)


# Find the indices of a Min./Max. of an array
# argmin(array, axis)
print()
print('Using np.argmin() and np.argmax():')
print('    Index of Min. of a:', np.argmin(a))
print('    Index of Max. along rows of a:', np.argmax(a, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Min. of a: 0
Max of a: 11
Max along columns: [ 8  9 10 11]
Min along rows: [0 4 8]

Using np.argmin() and np.argmax():
    Index of Min. of a: 0
    Index of Max. along rows of a: [3 3 3]


## Statistics Array Methods

### Exercise 1: Mean and Average

In [74]:
# Mean of entire array
a = np.arange(1,10).reshape(3,3)
mean = a.mean()

# Mean by Axes
mean_cols = a.mean(axis=0)
mean_rows = a.mean(axis=1)

print(a, '\n')
print('Mean:', mean)
print('Mean of each column:', mean_cols)
print('Mean of each row:', mean_rows)


# average() is a similar function to mean() that can also be used.
print()
print('Average:', np.average(a))

# can also average by axis
avg_cols = np.average(a, axis=0)
avg_rows = np.average(a, axis=1)
print('Avg. of each column:', avg_cols)
print('Avg. of each row:', avg_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Mean: 5.0
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]

Average: 5.0
Avg. of each column: [4. 5. 6.]
Avg. of each row: [2. 5. 8.]


### Exercise 2: Standard Deviation

In [80]:
# Can find the standard deviation of the elements in the entire array
a = np.ones([1,4])
b = np.arange(5,11)

print(a, '\n')
print(b, '\n')

std_a = a.std()
std_b = b.std()

# can find the std. dev. by axis as well
b.shape = [2,3]
std_b_cols = b.std(axis=0)
std_b_rows = b.std(axis=1)

print('Std. Dev. a:', std_a)
print('Std. Dev. b:', std_b, '\n\n')
print(b, '\n')
print('Std. Dev. b columns:', std_b_cols)
print('Std. Dev. b rows:', std_b_rows)

[[1. 1. 1. 1.]] 

[ 5  6  7  8  9 10] 

Std. Dev. a: 0.0
Std. Dev. b: 1.707825127659933 


[[ 5  6  7]
 [ 8  9 10]] 

Std. Dev. b columns: [1.5 1.5 1.5]
Std. Dev. b rows: [0.81649658 0.81649658]


### Exercise 3: Variance

In [81]:
var_b = b.var()
var_b_cols = b.var(axis=0)
var_b_rows = b.var(axis=1)

print(b, '\n')
print('Variance b:', var_b)
print('Var. b columns:', var_b_cols)
print('Var. b rows:', var_b_rows)

[[ 5  6  7]
 [ 8  9 10]] 

Variance b: 2.9166666666666665
Var. b columns: [2.25 2.25 2.25]
Var. b rows: [0.66666667 0.66666667]


## Other Useful Methods

### Exercise 1: Clip

In [91]:
# Clip - setting values that are outside of the given bounds to one of the bounds
# if n < min: n = min, if m > max: m = max

# Returns a copy of the original with all values within bounds given.

# bounds:
lower = 18
upper = 26

a = np.linspace(15,30,9)
print('original:')
print(a, '\n')

b = a.clip(lower, upper)
print('with lower and upper bounds:')
print(b, '\n')

c = a.clip(lower)
print('with lower bound only:')
print(c, '\n')

d = a.clip(None,upper)
print('with upper bound only:')
print(d)

original:
[15.    16.875 18.75  20.625 22.5   24.375 26.25  28.125 30.   ] 

with lower and upper bounds:
[18.    18.    18.75  20.625 22.5   24.375 26.    26.    26.   ] 

with lower bound only:
[18.    18.    18.75  20.625 22.5   24.375 26.25  28.125 30.   ] 

with upper bound only:
[15.    16.875 18.75  20.625 22.5   24.375 26.    26.    26.   ]


### Exercise 2: Peak to Peak

In [96]:
# Calculates the difference from the lowest value to the highest value in an array.
a = np.array([[1,7,6,4], [9,2,8,5], [3, 12, 10, 0]])
ptp_a = a.ptp()

# Can be used along axes as well
ptp_cols = a.ptp(axis=0)
ptp_rows = a.ptp(axis=1)

print(a, '\n')
print('ptp a:', ptp_a)
print('ptp cols:', ptp_cols)
print('ptp rows:', ptp_rows)

[[ 1  7  6  4]
 [ 9  2  8  5]
 [ 3 12 10  0]] 

ptp a: 12
ptp cols: [ 8 10  4  5]
ptp rows: [ 6  7 12]
